FROM python:3.8
WORKDIR /G:/Usuarios/Ariel Chumbita/Desktop/ARIEL/CURSOS Y FORMACION/DATA ENGINEERING - CODER HOUSE/DataEngineering/Clase 09/ejemplo_dockerfile
COPY hola_mundo.py .
CMD ["python", "-u", "hola_mundo.py"]